# Generated by Django 5.0.1 on 2024-01-25 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_devicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='company@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='phonenumber',
            field=models.CharField(default='01****', max_length=100),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('start_plan_set', models.DateTimeField(auto_now_add=True)),
                ('end_plan_date', models.DateTimeField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset.company')),
            ],
        ),
    ]
